### ISSUE TITLE
[Gameplay] Toad's bullets and powerups are hard to see when he's taking damage

### ISSUE THREAD

**Issue by suttonwilliamd** [omfgitsatoad/wizard-vs-toad#1]
Is this intended as part of the difficulty (like the Toad's HP, I assume you tested and realize how high it is)?

**Comment by jfetkotto** [comment]
The game was made as a fun little project. I never intended for it to be a fully fleshed out game. So there are lots of things i'd do differently. Cheers for the feedback.

**Comment by suttonwilliamd** [comment]
Would you accept PRs for keeping it up to date?  I'd even implement some of the aforementioned "lots of things" that you'd do differently.

I'm nearly done with the 11.1 update.

I can tell this is a fun little project for you, and that's awesome.  I just would like to keep the fun going while staying true to the project (which is to say, what you intended, and not necessarily how the project ends up literally translated into newer versions)

**Comment by jfetkotto** [comment]
I don't think i'd be too committed to checking things, but If you want to fork and develop it further i'd happily add a link to your updated version.

**Comment by suttonwilliamd** [comment]
I understand, thanks!  :)
